// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkjldcchsihoguesmlvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZramxkY2Noc2lob2d1ZXNtbHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDQyMDYsImV4cCI6MjA3MzUyMDIwNn0.m-thNZksehXH3S1Ws6kVL2a_TjGxIE_Itocmo10kQWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});